services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3752:3752"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/public
      - /node_modules
